version: '3.8'
services:
  gcwebx:
    image: docker.pkg.github.com/tschuehly/gcwebx/gcwebxbackend:latest
    expose:
      - "8080"
    depends_on:
      - db

  gcwebxfrontend:
    image: docker.pkg.github.com/tschuehly/gcwebx/gcwebxfrontend:latest
    ports:
      - "80:80"
    depends_on:
      - gcwebx
    command: [nginx-debug, '-g', 'daemon off;']
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    #expose:
     # - "5432"