version: '3.8'
services:
  gcwebx:
    build:
      context: ./
      dockerfile: DockerfileDev
    volumes:
      - ./:/usr/src/gcwebx
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"