version: '3.8'
services:
  gcwebx:
    build:
      context: ./
      dockerfile: DockerfileDev
    volumes:
      - ./:/usr/src/gcwebx
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    expose:
      - "5432"
    #volumes:
      #- ./userTest.sql:/docker-entrypoint-initdb.d/userTest.sql