version: '3.8'
services:
  gcwebx:
    build: .
    expose:
      - "8080"

  gcwebxfrontend:
    build: gcwebxfrontend
    ports:
      - "80:80"
    depends_on:
      - gcwebx
    command: [nginx-debug, '-g', 'daemon off;']