version: '3.8'
services:
  gcwebx:
    build: .
    expose:
      - "8080"
    depends_on:
      - db

  gcwebxfrontend:
    build: gcwebxfrontend
    ports:
      - "80:80"
    depends_on:
      - gcwebx
    command: [nginx-debug, '-g', 'daemon off;']
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    expose:
      - "5432"