spring:
  datasource:
    url: jdbc:h2:file:./data/demo
    driverClassName: org.h2.Driver
    username: sa
    password: password
#TODO: CHANGE Password to not appear in GIT
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true