spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres # jdbc:postgresql://db:5432/postgres for deployment  ||  jdbc:postgresql://localhost:5432/postgres for development
    username: postgres
    password: password
  profiles:
    active: development

    #TODO: CHANGE Password to not appear in GIT

    initialization-mode: always
  #TODO: CHANGE Password to not appear in GIT
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    console:
      enabled: true
#logging:
 # level:
    #org.springframework: DEBUG
    #senabled: true