 insert into member (member_Id, name, teamspeak_Id, general_Info, date_of_birth, join_date, acceptance_Date, editor, warnings, gamer_Tag, deleted, rank, twitter, twitch, youtube, card_Img) values (1, 'Raphicerus campestris', '30576281963697', 'quisque porta volutpat erat', '2017-08-09', '2015-01-05', '2015-06-04', 'dynamic', 4, 'dui nec nisi', true, 'donec semper sapien a libero nam dui proin leo', 'creativecommons.org/viverra/pede/ac/diam.json', 'posterous.com/vestibulum/eget/vulputate.html', 'flickr.com/in/ante.xml', 'ash.jpg');
 insert into member (member_Id, name, teamspeak_Id, general_Info, date_of_birth, join_date, acceptance_Date, editor, warnings, gamer_Tag, deleted, rank, twitter, twitch, youtube, card_Img) values (2, 'Numida meleagris', '060494480073388093', 'ut tellus nulla', '2018-09-09', '2011-04-19', '2019-07-14', 'Progressive', 7, 'penatibus et magnis dis', false, '1', 'rediff.com/velit/id/pretium/iaculis/diam.jpg', 'nsw.gov.au/nisi/nam/ultrices/libero/non/mattis.aspx', 'redcross.org/integer/aliquet/massa/id/lobortis.json', 'jackal.jpg');
 insert into member (member_Id, name, teamspeak_Id, general_Info, date_of_birth, join_date, acceptance_Date, editor, warnings, gamer_Tag, deleted, rank, twitter, twitch, youtube, card_Img) values (3, 'Recurvirostra avosetta', '3531560949303247', 'id lobortis convallis', '2013-03-31', '2014-05-21', '2019-04-20', 'monitoring', 10, 'amet eleifend', false, 'a odio in hac habitasse platea dictumst', 'phpbb.com/varius/ut/blandit/non/interdum/in.jsp', 'hatena.ne.jp/dolor.png', 'nymag.com/a.png', 'fuze.jpg');
 insert into member (member_Id, name, teamspeak_Id, general_Info, date_of_birth, join_date, acceptance_Date, editor, warnings, gamer_Tag, deleted, rank, twitter, twitch, youtube, card_Img) values (4, 'Papio cynocephalus', '6759470323093075', 'volutpat dui maecenas', '2011-05-05', '2019-09-21', '2012-05-12', 'cohesive', 3, 'cursus vestibulum', true, 'augue vel accumsan tellus nisi eu', 'google.fr/quis/tortor/id.jsp', 'digg.com/vestibulum/sit/amet/cursus/id/turpis/integer.jpg', 'google.com.hk/nisl/ut/volutpat/sapien.png', 'iq.jpg');
 insert into member (member_Id, name, teamspeak_Id, general_Info, date_of_birth, join_date, acceptance_Date, editor, warnings, gamer_Tag, deleted, rank, twitter, twitch, youtube, card_Img) values (5, 'Ratufa indica', '3575265006324741', 'sodales sed tincidunt eu felis', '2012-08-14', '2011-01-03', '2013-11-03', 'interface', 2, 'praesent blandit lacinia erat vestibulum', true, 'in faucibus orci luctus et', 'diigo.com/erat/eros/viverra/eget/congue/eget.json', 'paypal.com/massa/volutpat/convallis.xml', 'craigslist.org/nam/dui.js', 'mute.jpg');
 insert into member (member_Id, name, teamspeak_Id, general_Info, date_of_birth, join_date, acceptance_Date, editor, warnings, gamer_Tag, deleted, rank, twitter, twitch, youtube, card_Img) values (6, 'Nannopterum harrisi', '3543856318012328', 'morbi porttitor lorem id ligula', '2013-09-23', '2013-02-08', '2019-10-20', 'project', 4, 'turpis integer aliquet massa', false, 'enim lorem ipsum dolor sit amet consectetuer', 'etsy.com/donec.js', 'twitpic.com/neque/aenean/auctor.html', 'squidoo.com/fermentum.xml', 'bandit.jpg');
 insert into member (member_Id, name, teamspeak_Id, general_Info, date_of_birth, join_date, acceptance_Date, editor, warnings, gamer_Tag, deleted, rank, twitter, twitch, youtube, card_Img) values (7, 'Varanus albigularis', '56022156023294172', 'quam pharetra magna', '2016-11-10', '2014-03-28', '2011-12-08', 'User-centric', 10, 'a ipsum integer', false, 'id sapien in sapien iaculis congue vivamus metus', 'jiathis.com/sodales/sed/tincidunt/eu.html', 'bandcamp.com/cubilia/curae/duis/faucibus/accumsan/odio.aspx', 'blog.com/magna/bibendum/imperdiet.aspx', null);
 insert into member (member_Id, name, teamspeak_Id, general_Info, date_of_birth, join_date, acceptance_Date, editor, warnings, gamer_Tag, deleted, rank, twitter, twitch, youtube, card_Img) values (8, 'Paraxerus cepapi', '379887685546072', 'integer ac leo pellentesque', '2020-02-25', '2016-04-04', '2014-01-13', 'Centralized', 10, 'ante ipsum primis', true, 'pretium nisl ut volutpat sapien arcu sed', 'nifty.com/ut/tellus/nulla/ut/erat.jpg', 'elpais.com/amet.html', 'macromedia.com/in/eleifend/quam/a/odio/in.jsp', null);
 insert into member (member_Id, name, teamspeak_Id, general_Info, date_of_birth, join_date, acceptance_Date, editor, warnings, gamer_Tag, deleted, rank, twitter, twitch, youtube, card_Img) values (9, 'Phoenicopterus ruber', '201520750084315', 'sit amet nulla quisque', '2018-01-20', '2011-01-25', '2015-07-24', 'Team-oriented', 3, 'sit amet consectetuer adipiscing', null, 'pede morbi porttitor lorem id ligula suspendisse ornare', 'people.com.cn/at/diam/nam/tristique.jpg', 'biglobe.ne.jp/dictumst/maecenas/ut.aspx', 'yahoo.co.jp/tortor/sollicitudin/mi/sit/amet/lobortis.js', null);
 insert into member (member_Id, name, teamspeak_Id, general_Info, date_of_birth, join_date, acceptance_Date, editor, warnings, gamer_Tag, deleted, rank, twitter, twitch, youtube, card_Img) values (10, 'Eolophus roseicapillus', '5007667887792628', 'cubilia curae donec', '2017-04-07', '2012-09-16', '2012-05-23', 'parallelism', 4, 'blandit ultrices enim', null, 'semper est quam pharetra magna ac consequat metus sapien ut', 'stumbleupon.com/nonummy/integer/non/velit.jsp', 'spotify.com/elementum/eu.png', 'multiply.com/amet/eleifend/pede/libero/quis/orci/nullam.aspx', null);
 insert into member (member_Id, name, teamspeak_Id, general_Info, date_of_birth, join_date, acceptance_Date, editor, warnings, gamer_Tag, deleted, rank, twitter, twitch, youtube, card_Img) values (11, 'Cacatua tenuirostris', '5610282987917122', 'vestibulum ante ipsum primis', '2018-12-15', '2013-03-20', '2016-09-28', 'bi-directional', 3, 'morbi odio odio elementum', false, 'maecenas tincidunt lacus at velit vivamus vel nulla eget', 'guardian.co.uk/venenatis/turpis/enim/blandit/mi/in/porttitor.xml', 'ameblo.jp/penatibus/et/magnis.xml', 'accuweather.com/in/sapien/iaculis/congue/vivamus.jpg', null);
 insert into member (member_Id, name, teamspeak_Id, general_Info, date_of_birth, join_date, acceptance_Date, editor, warnings, gamer_Tag, deleted, rank, twitter, twitch, youtube, card_Img) values (12, 'Scolopax minor', '4041373366487092', 'iaculis justo in', '2019-11-04', '2011-01-31', '2016-03-09', 'hardware', 10, 'nec dui luctus rutrum nulla', true, 'at feugiat non pretium quis', 'yahoo.com/amet/nunc/viverra/dapibus/nulla/suscipit/ligula.jpg', 'independent.co.uk/eleifend/pede/libero/quis/orci.aspx', 'unicef.org/consectetuer/adipiscing/elit/proin.xml', null);
 insert into member (member_Id, name, teamspeak_Id, general_Info, date_of_birth, join_date, acceptance_Date, editor, warnings, gamer_Tag, deleted, rank, twitter, twitch, youtube, card_Img) values (13, 'Macropus agilis', '3569353521491431', 'quis augue luctus tincidunt nulla', '2012-09-05', '2014-05-11', '2012-02-19', 'attitude', 2, 'lobortis est', true, 'platea dictumst maecenas ut massa', 'gmpg.org/ut/volutpat/sapien/arcu/sed/augue.json', 'netscape.com/condimentum/neque/sapien.png', 'tripod.com/ultrices/aliquet/maecenas/leo/odio/condimentum.jsp', null);
 insert into member (member_Id, name, teamspeak_Id, general_Info, date_of_birth, join_date, acceptance_Date, editor, warnings, gamer_Tag, deleted, rank, twitter, twitch, youtube, card_Img) values (14, 'Phoeniconaias minor', '6767175274077763306', 'massa donec dapibus', '2013-11-30', '2012-03-19', '2016-08-25', 'bandwidth-monitored', 1, 'nisl duis ac nibh', true, 'proin eu mi nulla ac enim in tempor turpis nec', 'pbs.org/nulla.js', 'edublogs.org/ridiculus.jpg', 'google.co.jp/ut/rhoncus/aliquet/pulvinar/sed/nisl/nunc.jsp', null);
 insert into member (member_Id, name, teamspeak_Id, general_Info, date_of_birth, join_date, acceptance_Date, editor, warnings, gamer_Tag, deleted, rank, twitter, twitch, youtube, card_Img) values (15, 'Ateles paniscus', '201501523201089', 'curae donec pharetra magna vestibulum', '2017-08-31', '2018-09-01', '2013-08-11', 'encryption', 3, 'in leo maecenas pulvinar', true, 'porta volutpat erat quisque erat eros', 'skyrock.com/luctus/et/ultrices/posuere.xml', 'bing.com/mattis.js', 'qq.com/vehicula/condimentum/curabitur.aspx', null);
 insert into member (member_Id, name, teamspeak_Id, general_Info, date_of_birth, join_date, acceptance_Date, editor, warnings, gamer_Tag, deleted, rank, twitter, twitch, youtube, card_Img) values (16, 'Giraffe camelopardalis', '3553804789778206', 'donec odio justo sollicitudin ut', '2013-04-08', '2018-08-26', '2018-08-09', 'architecture', 1, 'interdum eu tincidunt', false, 'consequat in consequat ut nulla sed accumsan felis ut at', 'mtv.com/elementum/nullam/varius/nulla.json', 'ibm.com/pede/libero/quis/orci/nullam/molestie/nibh.html', 'twitter.com/quis/turpis/sed/ante/vivamus/tortor/duis.aspx', null);

INSERT INTO "PUBLIC"."TEAM" VALUES(1, 'rainbowsix', 'donec semper sapien a libero nam dui proin leo', 'Team 1');
INSERT INTO "PUBLIC"."TEAM" VALUES(2, 'valorant', 'duis faucibus accumsan odio curabitur convallis duis consequat', 'Team2');

INSERT INTO "PUBLIC"."TEAM_MEMBERS" VALUES(1, 1);
INSERT INTO "PUBLIC"."TEAM_MEMBERS" VALUES(1, 2);
INSERT INTO "PUBLIC"."TEAM_MEMBERS" VALUES(1, 3);

INSERT INTO "PUBLIC"."WEBSITE_USER" VALUES(1, 'admin@example.com', '$2y$12$lBKIcjeqv2IXQyJdjwNgKuItpQA7T4bAGcZdyrLvEAOm8r5aPlUlK', TRUE, TRUE, TRUE, TRUE, TRUE, 'admin');
INSERT INTO "PUBLIC"."WEBSITE_USER" VALUES(3, NULL, '$2a$10$gQidlZ2fMGpRi/IyUm7M7.kzeE2TyWty6p4OVJWlTfv9R97Go.Lye', FALSE, FALSE, TRUE, FALSE, TRUE, 'moderator');

INSERT INTO "PUBLIC"."MATCH" VALUES(1, TIMESTAMP '2020-10-12 20:18:00', 'Ewave', 'https://ewave-esports.de/wp-content/uploads/2019/11/ewave-esports-withe.png', 2, 0, 'DESBL ADVANCED LEAGUE', 1);