name: Docker Build and Deploy
on: [pull_request] 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker build
        run: | 
          docker build . -t tschuehly/gcwebx
          docker build ./gcwebxFrontend
